apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperliquid-pruner
  labels:
    app: hyperliquid-pruner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperliquid-pruner
  template:
    metadata:
      labels:
        app: hyperliquid-pruner
    spec:
      imagePullSecrets:
        - name: ecr-secret
      securityContext:
        fsGroup: 10000
      containers:
      - name: hyperliquid-pruner
        image: 609193078125.dkr.ecr.us-east-1.amazonaws.com/hyperliquid-pruner
        volumeMounts:
        - name: data-volume
          mountPath: /home/hluser/hl/data
        securityContext:
          runAsUser: 0
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: hyperliquid-pvc

      tolerations:
        - key: "hyperliquid-node"
          operator: "Equal"
          value: "hyperliquid-node"
          effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: hyperliquid-node
